### ISSUE TITLE
The Voting function seems to fail (ropsten network)

### ISSUE THREAD

**Issue by jancumps** [Infineon/BlockchainSecurity2Go-Android#1]
I used the voting function, with a Security 2Go card that has 0.1 ether on it.
The app reports success,  [but when looking at the contract](https://ropsten.etherscan.io/address/0x104d919b299dbbbea258a41e2e910c29c551bf17), the last transaction is from 60 days ago, and my 3 test votes do not arrive.
Also, the little vote cost is not subtracted from the card I'm using....

![image](https://user-images.githubusercontent.com/5400863/76710175-8e698980-6705-11ea-97a1-90e4805b2ccb.png)

**Comment by ahoeller** [comment]
Maybe you have to increase the gas value. Could you try this?

**Comment by jancumps** [comment]
Thank you. You are correct.

[I just tested with Gas price 400 GWEI and limit 80000....](https://ropsten.etherscan.io/tx/0xc200369a3b3ce0dacc8e3a660cba1f171805a448675e3ec5c4c82c224f83eaba)

![image](https://user-images.githubusercontent.com/5400863/78665680-7df89900-78d6-11ea-81e7-c177340976c8.png)


The error is OK, because true. It means that the contract system works!

**Comment by jancumps** [comment]
Successful one:
![image](https://user-images.githubusercontent.com/5400863/78679366-69260080-78ea-11ea-9309-741bfa20ba4a.png)
